name: Challenge 5 Environment Training Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        # Crucial step: Upgrade dependency tools first and install requirements
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Rely solely on the 'creds' secret, which contains all necessary SPN details (client-id, secret, tenant-id)
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Trigger Dev Training Job
        # Ensure your workspace name and resource group are correct in the below commands if they are not the defaults.
        # This command uses the registered 'diabetes-dev-folder' data asset.
        run: |
          az ml job create --file azure-ml/job.yml --set inputs.training_data='azureml:diabetes-dev-folder:latest' --stream

  production:
    needs: experiment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Rely solely on the 'creds' secret for production environment
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Trigger Prod Training Job
        # This command uses the registered 'diabetes-prod-folder' data asset.
        run: |
          az ml job create --file azure-ml/job.yml --set inputs.training_data='azureml:diabetes-prod-folder:latest' --stream
