name: Challenge 5 Environment Training Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        # Upgrades pip and setuptools to prevent build errors and installs requirements (including updated mlflow)
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Uses the full Service Principal JSON secret, resolving the login conflict
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Trigger Dev Training Job
        run: |
          az ml job create --file azure-ml/job.yml \
          --set inputs.training_data='azureml:diabetes-dev-folder:latest' \
          --resource-group mlops-rg \
          --workspace-name mlops-ws \
          --stream

  production:
    needs: experiment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Trigger Prod Training Job
        run: |
          az ml job create --file azure-ml/job.yml \
          --set inputs.training_data='azureml:diabetes-prod-folder:latest' \
          --resource-group mlops-rg \
          --workspace-name mlops-ws \
          --stream
